### ISSUE TITLE
Filtering for read2 with -f 630 produces an empty bam file

### ISSUE THREAD

**Issue by croth1** [skrakau/sim_iCLIP#1]
Hi, first of all a big thanks for providing all data & code - makes reproducing super easy! :+1: 

In the wiki you discard read1 with following command:

`samtools view -hb -f 630 rna-seq.bam -o rna-seq.R2.bam`

This outputs an empty bam file for me. Is 630 a typo?

If I am not mistaken these are the selected flags:

- [ ] 1 0x1 template having multiple segments in sequencing
- [x] 2 0x2 each segment properly aligned according to the aligner
- [x] 4 0x4 segment unmapped
- [ ] 8 0x8 next segment in the template unmapped
- [x] 16 0x10 SEQ being reverse complemented
- [x] 32 0x20 SEQ of the next segment in the template being reverse complemented
- [x] 64 0x40 the first segment in the template
- [ ] 128 0x80 the last segment in the template
- [ ] 256 0x100 secondary alignment
- [x] 512 0x200 not passing filters, such as platform/vendor quality controls
- [ ] 1024 0x400 PCR or optical duplicate
- [ ] 2048 0x800 supplementary alignment

Thanks a lot! :-)

**Comment by skrakau** [comment]
Thanks for reporting this!

Indeed, it should be 130, I corrected it in the wiki.
